title: Cloud Lunch and Learn Sessions
description: Cloud Lunch and Learn is a community initiative, provided by the community, for the community, to allow everyone to learn with sessions related to the Cloud, while they are enjoying their lunch and break.
             Also, we want to enable anyone to contribute with sessions or any contribution to improve the systems being used in this initiative.
             Initially, all sessions will be managed on the Sessionize event's page (https://sessionize.com/cloud-lunch-and-learn-2020/) and the sessions will be delivered using Microsoft Teams Meeting.
             For more information, please feel free to contact me and I will share with you all the info.
theme: jekyll-theme-cayman
